In [10]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential



In [11]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0


In [4]:

train_datagen = ImageDataGenerator(rescale=1./255,
                                   rotation_range = 40,
                                   width_shift_range = 0.2,
                                   height_shift_range=0.2,
                                   shear_range= 0.2,
                                   horizontal_flip= True,
                                   vertical_flip = True)

valid_datagen = ImageDataGenerator(rescale = 1./255)

train_dir_path = "ocr-data/data/training_data/"
valid_dir_path = "ocr-data/data/testing_data"

train_data = train_datagen.flow_from_directory(train_dir_path,
                                               target_size = (150,150),
                                               class_mode='categorical',
                                               seed = 42)

valid_data = valid_datagen.flow_from_directory(valid_dir_path,
                                               target_size = (150,150),
                                               class_mode = 'categorical',
                                               seed = 42)


Found 20628 images belonging to 36 classes.
Found 1008 images belonging to 36 classes.


In [5]:
from pathlib import Path
class_name = np.array(sorted(item.name for item in Path(train_dir_path).glob("*")))
print(class_name)

['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' 'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H'
 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


In [6]:
len(class_name)

36

In [12]:
model_1 = Sequential([
    layers.Conv2D(16,3, activation = "relu", input_shape = (150,150,2)),
    layers.Conv2D(32,3,activation = "relu"),
    layers.MaxPool2D(2),
    layers.Conv2D(64,3, activation = "relu"),
    layers.MaxPool2D(2),
    layers.Conv2D(64,3, activation = "relu"),
    layers.MaxPool2D(2),
    layers.Conv2D(64,3, activation = "relu"),
    layers.MaxPool2D(2),
    layers.Flatten(),
    layers.Dense(300, activation = "relu"),
    layers.Dense(36, activation = "softmax")
])

model_1.compile(loss = "categorical_crossentropy",
                optimizer = "rmsprop",
                metrics = ["accuracy"])

history_1 = model_1.fit(train_data,
                      epochs = 10,
                      steps_per_epoch = len(train_data),
                      validation_data = valid_data,
                      validation_steps = len(valid_data))

Epoch 1/10
645/645 [==============================] - 409s 633ms/step - loss: 3.0324 - accuracy: 0.1428 - val_loss: 1.5543 - val_accuracy: 0.4563
Epoch 2/10
645/645 [==============================] - 305s 472ms/step - loss: 1.8904 - accuracy: 0.3968 - val_loss: 0.8578 - val_accuracy: 0.7024
Epoch 3/10
645/645 [==============================] - 308s 478ms/step - loss: 1.3458 - accuracy: 0.5623 - val_loss: 0.4564 - val_accuracy: 0.8423
Epoch 4/10
645/645 [==============================] - 317s 492ms/step - loss: 1.0643 - accuracy: 0.6468 - val_loss: 0.3366 - val_accuracy: 0.8720
Epoch 5/10
645/645 [==============================] - 320s 496ms/step - loss: 0.9080 - accuracy: 0.7016 - val_loss: 0.3275 - val_accuracy: 0.8552
Epoch 6/10
645/645 [==============================] - 318s 492ms/step - loss: 0.7904 - accuracy: 0.7400 - val_loss: 0.2774 - val_accuracy: 0.9067
Epoch 7/10
645/645 [==============================] - 319s 495ms/step - loss: 0.7236 - accuracy: 0.7628 - val_loss: 0.3068 -

In [13]:
model_1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_5 (Conv2D)           (None, 148, 148, 16)      448       
                                                                 
 conv2d_6 (Conv2D)           (None, 146, 146, 32)      4640      
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 73, 73, 32)       0         
 2D)                                                             
                                                                 
 conv2d_7 (Conv2D)           (None, 71, 71, 64)        18496     
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 35, 35, 64)       0         
 2D)                                                             
                                                                 
 conv2d_8 (Conv2D)           (None, 33, 33, 64)       

In [16]:
exp_path = "exp.png"

In [43]:
def load_and_prep_data(filename, filesize = [150,150]):
  # read the images
  img = tf.io.read_file(filename)
  # decode the images
  img = tf.io.decode_png(contents=img, channels = 3)
  # resize the image 
  img = tf.image.resize(img , size = filesize)
  img = img/255.
  # expand the dims
  img = tf.expand_dims(img, axis = 0)
  

  return img

     

In [44]:
image = load_and_prep_data(exp_path)
image

<tf.Tensor: shape=(1, 150, 150, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dty

In [45]:
img_class =  model_1.predict(image)

1/1 [==============================] - 0s 165ms/step


train_data[0][0]

In [46]:
img_class

array([[1.6296623e-02, 3.1790589e-03, 1.5552310e-05, 6.8074892e-09,
        9.1790349e-07, 2.4029737e-06, 1.0140587e-04, 7.0969269e-05,
        2.4061428e-06, 1.1326114e-04, 1.4422812e-06, 1.0392887e-05,
        3.8947041e-05, 5.6872419e-03, 2.9825043e-07, 6.6310372e-07,
        1.8347937e-05, 2.0546755e-05, 9.6283042e-01, 7.5712502e-03,
        3.2190579e-05, 3.6798665e-04, 2.4240755e-06, 1.1609915e-03,
        7.1539159e-04, 3.6830895e-04, 7.7881188e-05, 7.0489688e-05,
        5.0531330e-06, 1.0214595e-06, 1.2184109e-03, 1.2156867e-05,
        1.0766952e-06, 6.7235624e-07, 1.7312525e-06, 2.1722685e-06]],
      dtype=float32)

In [48]:
f = np.round(img_class)

In [51]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [50]:
f[0][1]

0.0

In [53]:
len(f[0])
a= 0

In [56]:
for i in range(len(f[0])):
    if f[0][i] == 1:
        print(i)
        a= i

18


In [57]:
class_name[a]

'I'